[client_auth]
app_id = "client_qin-nz_0.1"
auth_code = "AuthCode"

[account]
broker_id = "9999"
user_id = "123456"  # 把这里改成你的用户名和密码
password = "123456"

[md]
front = ["tcp://180.168.146.187:10131"]
subscribe = ["SR007", "SR009"]
